In [1]:
import pandas as pd

se = pd.Series([1,2,3,4])

In [2]:
print(se)

0    1
1    2
2    3
3    4
dtype: int64


In [3]:
print(se.values)

[1 2 3 4]


In [4]:
# 從0開始，停在4，每次增加1
print(se.index)

RangeIndex(start=0, stop=4, step=1)


### 使用Dictionary

In [7]:
import pandas as pd

dict1 = {'a':100,'b':200,'c':300}
se = pd.Series(dict1)
print(se)

a    100
b    200
c    300
dtype: int64


In [8]:
print(se.index)

Index(['a', 'b', 'c'], dtype='object')


In [9]:
print(se.values)

[100 200 300]


### Series取值

In [10]:
se = pd.Series([1,2,3,4,5])
print(se[3])

4


In [11]:
# 印出2~4
print(se[1:4])

1    2
2    3
3    4
dtype: int64


### 使用二維串列建立DataFrame

In [17]:
import numpy as np


list1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
list1 = list1.reshape((4,5))

df = pd.DataFrame(list1,index=["小明","小花","小白","小東"],columns=["國文","英文","數學","社會","自然"])
df

國文  英文  數學  社會  自然
小明   1   2   3   4   5
小花   6   7   8   9  10
小白  11  12  13  14  15
小東  16  17  18  19  20

In [15]:
df.values

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
df.index

RangeIndex(start=0, stop=4, step=1)