## Numpy 逆矩陣
### [numpy.linalg.inv文檔](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html)
#### 計算一个方陣的逆，使之滿足 $ AA^{-1} = A^{-1} A = I $

In [1]:
import numpy as np

In [3]:
arr = np.array([[1, 3], [5, 7]])
print(arr)
arr_inv = np.linalg.inv(arr)
print(arr_inv)

[[1 3]
 [5 7]]
[[-0.875  0.375]
 [ 0.625 -0.125]]


## [eye文檔](https://numpy.org/devdocs/reference/generated/numpy.eye.html)
#### Return a 2-D array with ones on the diagonal and zeros elsewhere.Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [7]:
a = np.eye(3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
